### PR TITLE
Update info.plist

### PR DESCRIPTION
**Pull request by jrobichaud**
Made RightClick compatible with any frontApp

### CODE REVIEW

**Comment by vitorgalvao** [comment]
Thank you, but why is this useful? Just like the problem (introduced with later OS X versions) of this not working properly when on the Desktop (it ignores selections when right-clicking), so does the same happen with apps.

What’s the benefit, if it works generically and won’t let you act on what you might want? It also does not work in every app (like [Atom](https://atom.io)).

**Comment by jrobichaud** [comment]
I changed two things:
-removed the conditions that was making  sure the frontMost App was Finder
-made sure the forwarded event is to the frontMost App instead of Finder


In SourceTree and the Desktop it is working properly for me and just does nothing in not supported apps such as Sublime Text or Chrome.

I am on Yosemite 10.10.3

Jules Robichaud-Gagnon

**Comment by jrobichaud** [comment]
You were right about the Desktop however it does work in Xcode and SourceTree.

**Comment by vitorgalvao** [comment]
it does indeed work in Xcode, and on text selections, even! Nice surprise.

Thank you for the contribution.

**Pull request merged**
